name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clone checker-core
        run: git clone https://github.com/hromatizm/otus-patterns-checker-core.git
      
      - name: Publish checker-core to Maven local
        run: |
          cd otus-patterns-checker-core
          ./gradlew publishToMavenLocal

      - name: Build and test
        run: ./gradlew build

      - name: Check Kover coverage
        run: ./gradlew koverVerify
