name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_USER_HOME: ~/.m2  # Убедимся, что это единообразно

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clone checker-core
        run: git clone https://github.com/hromatizm/otus-patterns-checker-core.git

      - name: Publish redirect-core to Maven local
        run: ./gradlew publishToMavenLocal
        working-directory: ./redirect-core

      - name: Build and test
        run: gradle build

      - name: Check Kover coverage
        run: ./gradlew koverVerify
